//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Annouuncements> Annouuncements { get; set; }
        public virtual DbSet<ClockInApply> ClockInApply { get; set; }
        public virtual DbSet<Departments> Departments { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<LeaveRequests> LeaveRequests { get; set; }
        public virtual DbSet<OverTimeRequest> OverTimeRequest { get; set; }
        public virtual DbSet<ReviewStatus> ReviewStatus { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<WorkingDaySchedule> WorkingDaySchedule { get; set; }
        public virtual DbSet<Attendances> Attendances { get; set; }

        public System.Data.Entity.DbSet<AMS.Controllers.EmployeesCreateViewModel> EmployeesCreateViewModels { get; set; }

        public System.Data.Entity.DbSet<AMS.Models.OverTimeViewModel> OverTimeViewModels { get; set; }

        public System.Data.Entity.DbSet<AMS.Controllers.SerchAttendancesViewModel> SerchAttendancesViewModels { get; set; }

        public System.Data.Entity.DbSet<AMS.Models.LeaveIndexViewModel> LeaveIndexViewModels { get; set; }

        public System.Data.Entity.DbSet<AMS.Models.ClockInApplyViewModel> ClockInApplyViewModels { get; set; }

        public System.Data.Entity.DbSet<AMS.Controllers.AttendancesViewModel> AttendancesViewModels { get; set; }
    }
}
