//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employees
    {
        public string EmployeeID { get; set; }
        public string EmployeeName { get; set; }
        public string IDNumber { get; set; }
        public string DeputyPhone { get; set; }
        public string Deputy { get; set; }
        public string Marital { get; set; }
        public string Email { get; set; }
        public System.DateTime Birthday { get; set; }
        public Nullable<System.DateTime> Leaveday { get; set; }
        public System.DateTime Hireday { get; set; }
        public string Address { get; set; }
        public int? DepartmentID { get; set; }
        public string Phone { get; set; }
        public byte[] Photo { get; set; }
        public string JobStaus { get; set; }
        public string JobTitle { get; set; }
        public string EnglishName { get; set; }
        public Nullable<bool> gender { get; set; }
        public string Notes { get; set; }
        public string LineID { get; set; }
        public string Education { get; set; }
    }
}
