//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveRequests
    {
        public string LeaveRequestID { get; set; }
        public string EmployeeID { get; set; }
        public Nullable<System.DateTime> RequestTime { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public string LeaveType { get; set; }
        public string LeaveReason { get; set; }
        public int ReviewStatusID { get; set; }
        public Nullable<System.DateTime> ReviewTime { get; set; }
        public byte[] Attachment { get; set; }
        public byte[] Picture { get; internal set; }
    }
}
