//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public string EmployeeID { get; set; }
        public byte[] Password { get; set; }
        public Nullable<System.DateTime> LockOff { get; set; }
        public System.Guid Guid { get; set; }
        public Nullable<bool> LockEnabled { get; set; }
        public Nullable<int> WrongTimes { get; set; }
    }
}
